const assert = require('node:assert/strict');
const path = require('node:path');
const {spawn} = require('node:child_process');
const {chromium} = require('playwright');
const root = path.resolve(__dirname, '..');
(async () => {
 const server = spawn('python3', ['serve.py', '--port', '0'], {cwd:root, stdio:['ignore','pipe','pipe']});
 let browser;
 try {
  const origin = await new Promise((resolve,reject) => {server.stdout.on('data',d => {const m=String(d).match(/http:\/\/127\.0\.0\.1:\d+/);if(m)resolve(m[0]);});server.on('error',reject);});
  browser = await chromium.launch({channel:'chrome',headless:true,timeout:6000,args:['--enable-unsafe-swiftshader']});
  const page = await browser.newPage({viewport:{width:1440,height:940}});page.setDefaultTimeout(1600);
  const errors=[];page.on('pageerror',e=>errors.push(e.stack));page.on('console',m=>{if(m.type()==='error')errors.push(m.text());});
  await page.goto(origin+'/editor/',{waitUntil:'commit'});
  await page.waitForFunction(()=>window.editor?.placement&&editor.session&&!editor.session.loading&&document.querySelector('#viewport canvas'),null,{timeout:6000});
  await page.evaluate(()=>{
   editor.placement.setMovementMode('surface');
   const group=new THREE.Group();group.name='比例样件';group.position.set(2,2,0);group.scale.set(-2,3,4);group.rotation.order='YXZ';
   const child=new THREE.Mesh(new THREE.BoxGeometry(1,1,1),new THREE.MeshStandardMaterial());child.position.set(.7,.5,.2);group.add(child);
   editor.addObject(group);editor.select(group);
  });
  const read=()=>page.evaluate(()=>{const o=editor.scene.getObjectByName('比例样件'),b=new THREE.Box3().setFromObject(o,true);return{position:o.position.toArray(),scale:o.scale.toArray(),quaternion:o.quaternion.toArray(),bottom:b.min.y,center:b.getCenter(new THREE.Vector3()).toArray(),history:editor.history.undos.length};});
  const close=(a,b)=>a.every((x,i)=>Math.abs(x-b[i])<1e-7);
  const before=await read();
  const ratio=page.getByLabel('缩放比例（相对当前，%）',{exact:true});
  await ratio.fill('50');await page.getByRole('button',{name:'应用',exact:true}).click();
  let current=await read();assert(close(current.scale,[-1,1.5,2]));assert.equal(current.bottom,before.bottom);assert(close([current.center[0],current.center[2]],[before.center[0],before.center[2]]));assert.equal(current.history,before.history+1);
  await page.evaluate(()=>editor.undo());assert(close((await read()).scale,before.scale));assert(close((await read()).position,before.position));
  await page.evaluate(()=>editor.redo());assert(close((await read()).scale,[-1,1.5,2]));
  await ratio.fill('0');await page.getByRole('button',{name:'应用',exact:true}).click();assert.equal((await read()).history,current.history);
  assert(await page.evaluate(()=>[NaN,Infinity,-1,0,1e308].every(n=>editor.placement.scale(n)===false)),'invalid or overflowing scales are rejected');
  assert(close((await read()).scale,current.scale));
  await ratio.fill('200');await ratio.press('Enter');assert(close((await read()).scale,before.scale),'percentage entry supports keyboard and keeps mirror signs/aspect ratio');
  const x=page.getByLabel('X · 位置坐标（米）',{exact:true});
  const xBefore=(await read()).position[0];await x.fill(String(xBefore+.001));await x.press('Enter');
  assert(Math.abs((await read()).position[0]-xBefore-.001)<1e-9,'1 mm edits are accepted');
  const yaw=page.getByLabel('Y · 朝向角度（度）',{exact:true});await yaw.fill('0.1');await yaw.press('Enter');
  assert(await page.evaluate(()=>Math.abs(editor.selected.rotation.y-THREE.MathUtils.degToRad(.1))<1e-9&&editor.selected.rotation.order==='YXZ'),'0.1 degree edits retain Euler order');
  const step=page.getByLabel('每次转动角度（度）',{exact:true});await step.fill('7.3');await step.press('Tab');
  const turnBefore=await read();await page.getByRole('button',{name:'左转',exact:true}).click();
  assert(await page.evaluate(()=>Math.abs(editor.selected.rotation.y-THREE.MathUtils.degToRad(7.4))<1e-9),'custom angle adds without 45-degree snapping');
  current=await read();assert(Math.abs(current.bottom-turnBefore.bottom)<1e-8);assert(close(current.center,turnBefore.center));
  await page.evaluate(()=>editor.undo());assert(close((await read()).position,turnBefore.position));assert(close((await read()).quaternion,turnBefore.quaternion));
  await page.evaluate(()=>editor.placement.rotate(1,721.5));assert(await page.evaluate(()=>Math.abs(editor.selected.rotation.y-THREE.MathUtils.degToRad(1.6))<1e-9),'angles may wrap more than one full turn');
  await page.evaluate(()=>editor.undo());
  await page.evaluate(()=>editor.placement.contextAction('lock',editor.selected));
  assert(await ratio.isDisabled());assert(await x.isDisabled());assert(await yaw.isDisabled());assert(await page.getByRole('button',{name:'移动物品',exact:true}).isDisabled());
  assert(await page.evaluate(()=>!editor.placement.rotate(1)&&!editor.placement.scale(.5)),'locked models reject transforms');
  await page.evaluate(()=>editor.undo());
  const grabBefore=await read();await page.getByRole('button',{name:'移动物品',exact:true}).click();
  assert.equal(await page.evaluate(()=>editor.placement.object?.name),'比例样件');
  await ratio.fill('50');await page.getByRole('button',{name:'应用',exact:true}).click();
  assert.equal(await page.evaluate(()=>editor.placement.object?.name),'比例样件','percentage input preserves grab');
  assert.equal((await read()).history,grabBefore.history,'preview scaling does not create a history entry');
  const point=await page.evaluate(()=>{const v=new THREE.Vector3(0,0,1).project(editor.camera),r=document.querySelector('#viewport canvas').getBoundingClientRect();return{x:r.x+(v.x+1)*r.width/2,y:r.y+(1-v.y)*r.height/2};});
  await page.mouse.move(point.x,point.y);
  await page.evaluate(()=>document.querySelector('#viewport canvas').focus());
  const wheelBefore=await page.evaluate(()=>editor.placement.object.rotation.y);
  await page.mouse.wheel(0,2);await page.waitForTimeout(40);
  assert(Math.abs(await page.evaluate(()=>editor.placement.object.rotation.y)-wheelBefore-.4*Math.PI/180)<1e-7);
  await page.keyboard.down('Shift');await page.mouse.wheel(0,2);await page.keyboard.up('Shift');await page.waitForTimeout(40);
  assert(Math.abs(await page.evaluate(()=>editor.placement.object.rotation.y)-wheelBefore-.44*Math.PI/180)<1e-7,'Shift wheel gives fine continuous yaw');
  await page.keyboard.press('r');assert(Math.abs(await page.evaluate(()=>editor.placement.object.rotation.y)-wheelBefore-7.74*Math.PI/180)<1e-7,'R shares the custom angle');
  await page.getByRole('button',{name:'确认摆放',exact:true}).click();
  assert.equal((await read()).history,grabBefore.history+1);await page.evaluate(()=>editor.undo());assert(close((await read()).scale,grabBefore.scale));assert(close((await read()).position,grabBefore.position));assert(close((await read()).quaternion,grabBefore.quaternion));
  await page.evaluate(()=>editor.redo());assert.equal(await page.evaluate(()=>editor.placement.object),null);
  await page.screenshot({path:path.join(root,'.build_tmp/transforms.png')});
  assert.deepEqual(errors,[]);
  console.log('PASS: percentage shrink/grow, nonuniform/mirrored ratio preservation, invalid input, 1mm/0.1 degree edits, yaw beyond a turn, custom step/continuous/fine wheel, lock enforcement, move entry, combined grab undo/redo; console errors=0');
 } finally {if(browser)await browser.close();server.kill('SIGTERM');}
})().catch(e=>{console.error(e);process.exitCode=1;});
