function Strings() {

	const values = {

		'sidebar/project/camera': '画面视角',
		'sidebar/settings/shortcuts/perspective': '透视视角',
		'sidebar/settings/shortcuts/orthographic': '平面视角',

		'prompt/file/open': '您确定吗？未保存的数据将会丢失。',
		'prompt/file/failedToOpenProject': '无法打开项目！',
		'prompt/file/export/noMeshSelected': '未选择网格！',
		'prompt/file/export/noObjectSelected': '未选择对象！',
		'prompt/file/export/duplicateNames': '部分对象具有相同的名称。它们将被重命名以确保名称唯一。确定吗？',
		'prompt/script/remove': '你确定吗？',
		'prompt/history/clear': '撤销/重做历史记录将被清除。您确定吗？',
		'prompt/history/preserve': '历史将在会话之间保留。\n这可能会影响在处理纹理时的性能。',
		'prompt/history/forbid': '在播放场景时，撤消/重做被禁用。',
		'prompt/rendering/realistic/unsupportedMaterial': "写实预览只支持标准材质和物理材质，请先在「材质质感」中切换。",

		'command/AddObject': '添加对象',
		'command/AddScript': '添加脚本',
		'command/MoveObject': '移动对象',
		'command/MultiCmds': '多次更改',
		'command/RemoveObject': '删除对象',
		'command/RemoveScript': '删除脚本',
		'command/SetColor': '设置颜色',
		'command/SetGeometry': '设置几何图形',
		'command/SetGeometryValue': '设置几何值',
		'command/SetMaterialColor': '设置材质颜色',
		'command/SetMaterial': '设置材质',
		'command/SetMaterialMap': '设置材质贴图',
		'command/SetMaterialRange': '设置材料范围',
		'command/SetMaterialValue': '设置材料值',
		'command/SetMaterialVector': '设置材质矢量',
		'command/SetPosition': '设置位置',
		'command/SetRotation': '设置旋转',
		'command/SetScale': '设置比例',
		'command/SetScene': '设置布景',
		'command/SetScriptValue': '设置脚本值',
		'command/SetShadowValue': '设置阴影值',
		'command/SetTextureParameters': '设置纹理参数',
		'command/SetUuid': '设置 UUID',
		'command/SetValue': '设定值',

		'menubar/file': '文件',
		'menubar/file/new': '新建项目',
		'menubar/file/new/empty': "空白场景",
		'menubar/file/new/Arkanoid': '打砖块',
		'menubar/file/new/Camera': "相机演示",
		'menubar/file/new/Particles': '粒子',
		'menubar/file/new/Pong': '乒乓球',
		'menubar/file/new/Shaders': '着色器',
		'menubar/file/open': '打开',
		'menubar/file/save': '保存',
		'menubar/file/import': "导入模型（GLB / OBJ 等）",
		'menubar/file/export': '导出',

		'menubar/edit': '编辑',
		'menubar/edit/undo': '撤销',
		'menubar/edit/redo': '重做',
		'menubar/edit/center': '居中',
		'menubar/edit/clone': "克隆",
		'menubar/edit/delete': '删除',

		'menubar/add': '添加',
		'menubar/add/group': "物件组",

		'menubar/add/mesh': "基础形状",
		'menubar/add/mesh/plane': '平面',
		'menubar/add/mesh/box': "立方体",
		'menubar/add/mesh/capsule': '胶囊',
		'menubar/add/mesh/circle': '圆',
		'menubar/add/mesh/cylinder': '圆柱体',
		'menubar/add/mesh/ring': '环',
		'menubar/add/mesh/sphere': '球体',
		'menubar/add/mesh/dodecahedron': '十二面体',
		'menubar/add/mesh/icosahedron': '二十面体',
		'menubar/add/mesh/octahedron': '八面体',
		'menubar/add/mesh/tetrahedron': '四面体',
		'menubar/add/text': "立体文字",
		'menubar/add/mesh/torus': '圆环体',
		'menubar/add/mesh/torusknot': '环面纽结体',
		'menubar/add/mesh/tube': '管',
		'menubar/add/mesh/lathe': '酒杯',
		'menubar/add/mesh/sprite': '精灵',

		'menubar/add/light': "灯光",
		'menubar/add/light/ambient': '环境光',
		'menubar/add/light/directional': '平行光',
		'menubar/add/light/hemisphere': '半球光',
		'menubar/add/light/point': '点光源',
		'menubar/add/light/spot': '聚光灯',

		'menubar/add/camera': '摄像机',
		'menubar/add/camera/perspective': '透视相机',
		'menubar/add/camera/orthographic': '正交相机',

		'menubar/status/autosave': '自动保存',

		'menubar/view': '视图',
		'menubar/view/fullscreen': '全屏',
		'menubar/view/gridHelper': "地面网格",
		'menubar/view/cameraHelpers': "相机辅助线",
		'menubar/view/lightHelpers': "灯光辅助线",
		'menubar/view/skeletonHelpers': "骨骼辅助线",

		'menubar/render': '渲染',
		'menubar/render/image': '图片',
		'menubar/render/video': '视频',
		'menubar/render/quality': '质量',
		'menubar/render/cancel': '取消',

		'menubar/help': '帮助',
		'menubar/help/source_code': '源码',
		'menubar/help/icons': '图标组件包',
		'menubar/help/about': '关于',
		'menubar/help/manual': '手册',

		'sidebar/animations': '动画',
		'sidebar/animations/play': '播放',
		'sidebar/animations/stop': '暂停',
		'sidebar/animations/timescale': '时间缩放',

		'sidebar/scene': "场景物件列表",
		'sidebar/scene/background': '背景',
		'sidebar/scene/environment': "环境照明",
		'sidebar/scene/fog': "远景雾气",

		'sidebar/properties/object': "空间摆放",
		'sidebar/properties/geometry': "形状网格",
		'sidebar/properties/material': "材质质感",
		'sidebar/properties/script': '脚本',

		'sidebar/object/type': '类型',
		'sidebar/object/new': "重生成",
		'sidebar/object/uuid': '识别码',
		'sidebar/object/name': '名称',
		'sidebar/object/position': "位置坐标",
		'sidebar/object/rotation': "朝向角度",
		'sidebar/object/scale': "模型大小",
		'sidebar/object/fov': '视角',
		'sidebar/object/left': '左',
		'sidebar/object/right': '右',
		'sidebar/object/top': '上',
		'sidebar/object/bottom': '下',
		'sidebar/object/near': '近点',
		'sidebar/object/far': '远点',
		'sidebar/object/intensity': '强度',
		'sidebar/object/color': '颜色',
		'sidebar/object/groundcolor': "地面反射颜色",
		'sidebar/object/distance': '距离',
		'sidebar/object/angle': '角度',
		'sidebar/object/penumbra': "光斑柔边",
		'sidebar/object/decay': '衰减',
		'sidebar/object/shadow': '阴影',
		'sidebar/object/shadowIntensity': '阴影强度',
		'sidebar/object/shadowBias': '阴影偏移',
		'sidebar/object/shadowNormalBias': '阴影法线偏移',
		'sidebar/object/shadowRadius': '阴影半径',
		'sidebar/object/cast': "投射",
		'sidebar/object/receive': "接收",
		'sidebar/object/visible': '可见性',
		'sidebar/object/frustumcull': "隐藏画面外物件",
		'sidebar/object/renderorder': '渲染次序',
		'sidebar/object/userdata': '自定义数据',
		'sidebar/object/export': '导出JSON',

		'sidebar/geometry/type': '类型',
		'sidebar/geometry/new': "重生成",
		'sidebar/geometry/uuid': '识别码',
		'sidebar/geometry/name': '名称',
		'sidebar/geometry/bounds': "模型边界",
		'sidebar/geometry/userdata': '自定义数据',
		'sidebar/geometry/show_vertex_normals': '显示顶点法线',
		'sidebar/geometry/compute_vertex_normals': "重算法线（改善光照）",
		'sidebar/geometry/compute_vertex_tangents': "重算切线（改善贴图）",
		'sidebar/geometry/center': '居中',
		'sidebar/geometry/export': '导出JSON',
		'sidebar/geometry/morph': "形状变形目标",

		'sidebar/geometry/box_geometry/width': '宽度',
		'sidebar/geometry/box_geometry/height': '高度',
		'sidebar/geometry/box_geometry/depth': '深度',
		'sidebar/geometry/box_geometry/widthseg': '宽度分段',
		'sidebar/geometry/box_geometry/heightseg': '高度分段',
		'sidebar/geometry/box_geometry/depthseg': '深度分段',

		'sidebar/geometry/buffer_geometry/attributes': '属性',
		'sidebar/geometry/buffer_geometry/index': '索引',
		'sidebar/geometry/buffer_geometry/morphAttributes': '变形属性',
		'sidebar/geometry/buffer_geometry/morphRelative': '相对变形',

		'sidebar/geometry/capsule_geometry/radius': '半径',
		'sidebar/geometry/capsule_geometry/height': '高度',
		'sidebar/geometry/capsule_geometry/capseg': '胶囊分段',
		'sidebar/geometry/capsule_geometry/radialseg': '半径分段',
		'sidebar/geometry/capsule_geometry/heightseg': '高度分段',

		'sidebar/geometry/circle_geometry/radius': '半径',
		'sidebar/geometry/circle_geometry/segments': '分段',
		'sidebar/geometry/circle_geometry/thetastart': '弧度起点',
		'sidebar/geometry/circle_geometry/thetalength': '弧度长度',

		'sidebar/geometry/cylinder_geometry/radiustop': '顶部半径',
		'sidebar/geometry/cylinder_geometry/radiusbottom': '底部半径',
		'sidebar/geometry/cylinder_geometry/height': '高度',
		'sidebar/geometry/cylinder_geometry/radialsegments': '径向分段',
		'sidebar/geometry/cylinder_geometry/heightsegments': '高度分段',
		'sidebar/geometry/cylinder_geometry/openended': '开端',

		'sidebar/geometry/extrude_geometry/curveSegments': '曲线段',
		'sidebar/geometry/extrude_geometry/steps': '细分点数',
		'sidebar/geometry/extrude_geometry/depth': '深度',
		'sidebar/geometry/extrude_geometry/bevelEnabled': '启用斜角',
		'sidebar/geometry/extrude_geometry/bevelThickness': '斜角厚度',
		'sidebar/geometry/extrude_geometry/bevelSize': '斜角大小',
		'sidebar/geometry/extrude_geometry/bevelOffset': '斜角偏移量',
		'sidebar/geometry/extrude_geometry/bevelSegments': '斜角分段',
		'sidebar/geometry/extrude_geometry/shape': '转换图形',

		'sidebar/geometry/dodecahedron_geometry/radius': '半径',
		'sidebar/geometry/dodecahedron_geometry/detail': '面片分段',

		'sidebar/geometry/icosahedron_geometry/radius': '半径',
		'sidebar/geometry/icosahedron_geometry/detail': '面片分段',

		'sidebar/geometry/octahedron_geometry/radius': '半径',
		'sidebar/geometry/octahedron_geometry/detail': '面片分段',

		'sidebar/geometry/tetrahedron_geometry/radius': '半径',
		'sidebar/geometry/tetrahedron_geometry/detail': '面片分段',

		'sidebar/geometry/lathe_geometry/segments': '分段',
		'sidebar/geometry/lathe_geometry/phistart': '经度起点',
		'sidebar/geometry/lathe_geometry/philength': '经度长度',
		'sidebar/geometry/lathe_geometry/points': '点',

		'sidebar/geometry/plane_geometry/width': '宽度',
		'sidebar/geometry/plane_geometry/height': '长度',
		'sidebar/geometry/plane_geometry/widthsegments': '宽度分段',
		'sidebar/geometry/plane_geometry/heightsegments': '长度分段',

		'sidebar/geometry/ring_geometry/innerRadius': '内半径',
		'sidebar/geometry/ring_geometry/outerRadius': '外半径',
		'sidebar/geometry/ring_geometry/thetaSegments': '弧度分段',
		'sidebar/geometry/ring_geometry/phiSegments': '经度分段',
		'sidebar/geometry/ring_geometry/thetastart': '弧度起点',
		'sidebar/geometry/ring_geometry/thetalength': '弧度长度',

		'sidebar/geometry/text_geometry/text': "文字内容",
		'sidebar/geometry/text_geometry/size': "文字大小",
		'sidebar/geometry/text_geometry/depth': "凸起厚度",
		'sidebar/geometry/text_geometry/scale': "整体大小",
		'sidebar/geometry/text_geometry/curveseg': "曲线细分",
		'sidebar/geometry/text_geometry/bevelenabled': "边缘倒角",
		'sidebar/geometry/text_geometry/bevelthickness': "倒角厚度",
		'sidebar/geometry/text_geometry/bevelsize': "倒角大小",
		'sidebar/geometry/text_geometry/bevelOffset': "倒角偏移",
		'sidebar/geometry/text_geometry/bevelseg': "倒角细分",

		'sidebar/geometry/shape_geometry/curveSegments': '曲线段',
		'sidebar/geometry/shape_geometry/extrude': '拉伸',

		'sidebar/geometry/sphere_geometry/radius': '半径',
		'sidebar/geometry/sphere_geometry/widthsegments': '宽度分段',
		'sidebar/geometry/sphere_geometry/heightsegments': '长度分段',
		'sidebar/geometry/sphere_geometry/phistart': '经度起点',
		'sidebar/geometry/sphere_geometry/philength': '经度长度',
		'sidebar/geometry/sphere_geometry/thetastart': '纬度起点',
		'sidebar/geometry/sphere_geometry/thetalength': '纬度长度',

		'sidebar/geometry/torus_geometry/radius': '半径',
		'sidebar/geometry/torus_geometry/tube': '管厚',
		'sidebar/geometry/torus_geometry/radialsegments': '半径分段',
		'sidebar/geometry/torus_geometry/tubularsegments': '管厚分段',
		'sidebar/geometry/torus_geometry/arc': '弧度',

		'sidebar/geometry/torusKnot_geometry/radius': '半径',
		'sidebar/geometry/torusKnot_geometry/tube': '管厚',
		'sidebar/geometry/torusKnot_geometry/tubularsegments': '管厚分段',
		'sidebar/geometry/torusKnot_geometry/radialsegments': '半径分段',
		'sidebar/geometry/torusKnot_geometry/p': '管长弧度',
		'sidebar/geometry/torusKnot_geometry/q': '扭曲弧度',

		'sidebar/geometry/tube_geometry/path': '路径',
		'sidebar/geometry/tube_geometry/radius': '半径',
		'sidebar/geometry/tube_geometry/tube': '管厚',
		'sidebar/geometry/tube_geometry/tubularsegments': '管厚分段',
		'sidebar/geometry/tube_geometry/radialsegments': '半径分段',
		'sidebar/geometry/tube_geometry/closed': '闭合',
		'sidebar/geometry/tube_geometry/curvetype': '曲线类型',
		'sidebar/geometry/tube_geometry/tension': '张力',

		'sidebar/material/new': '更新',
		'sidebar/material/copy': '复制',
		'sidebar/material/paste': '粘贴',
		'sidebar/material/slot': '插槽',
		'sidebar/material/type': '类型',
		'sidebar/material/uuid': '识别码',
		'sidebar/material/name': '名称',
		'sidebar/material/program': '程序',
		'sidebar/material/info': '信息',
		'sidebar/material/vertex': '顶点',
		'sidebar/material/fragment': '片元',
		'sidebar/material/color': "颜色",
		'sidebar/material/depthPacking': '深度包装',
		'sidebar/material/roughness': "粗糙度",
		'sidebar/material/metalness': "金属感",
		'sidebar/material/reflectivity': '反射率',
		'sidebar/material/emissive': '自发光',
		'sidebar/material/specular': '高光',
		'sidebar/material/shininess': '高光大小',
		'sidebar/material/clearcoat': '清漆',
		'sidebar/material/clearcoatroughness': '清漆粗糙度',
		'sidebar/material/dispersion': '分散',
		'sidebar/material/ior': "折射率",
		'sidebar/material/iridescence': '彩虹色',
		'sidebar/material/iridescenceIOR': '彩虹色折射率',
		'sidebar/material/iridescenceThicknessMax': '彩虹色厚度',
		'sidebar/material/sheen': '光泽',
		'sidebar/material/sheenroughness': '光泽粗糙度',
		'sidebar/material/sheencolor': '光泽颜色',
		'sidebar/material/transmission': '透光',
		'sidebar/material/attenuationDistance': '衰减距离',
		'sidebar/material/attenuationColor': '衰减色',
		'sidebar/material/thickness': '厚度',
		'sidebar/material/vertexcolors': '顶点颜色',
		'sidebar/material/matcap': '材质捕获',
		'sidebar/material/map': '贴图',
		'sidebar/material/alphamap': '透明贴图',
		'sidebar/material/bumpmap': '凹凸贴图',
		'sidebar/material/normalmap': '法线贴图',
		'sidebar/material/clearcoatmap': '清漆贴图',
		'sidebar/material/clearcoatnormalmap': '清漆法线贴图',
		'sidebar/material/clearcoatroughnessmap': '清漆粗糙度贴图',
		'sidebar/material/displacementmap': '置换贴图',
		'sidebar/material/roughnessmap': '粗糙度贴图',
		'sidebar/material/metalnessmap': '金属贴图',
		'sidebar/material/specularmap': '高光贴图',
		'sidebar/material/iridescencemap': '彩虹色贴图',
		'sidebar/material/iridescencethicknessmap': '彩虹色厚度贴图',
		'sidebar/material/sheencolormap': '光泽颜色贴图',
		'sidebar/material/sheenroughnessmap': '光泽粗糙度贴图',
		'sidebar/material/envmap': '环境贴图',
		'sidebar/material/lightmap': '光照贴图',
		'sidebar/material/aomap': '环境光遮蔽贴图',
		'sidebar/material/emissivemap': '自发光贴图',
		'sidebar/material/gradientmap': '渐变贴图',
		'sidebar/material/transmissionmap': '透光贴图',
		'sidebar/material/thicknessmap': '厚度贴图',
		'sidebar/material/side': '面',
		'sidebar/material/size': '大小',
		'sidebar/material/sizeAttenuation': '大小衰减',
		'sidebar/material/flatShading': '平面着色',
		'sidebar/material/blending': '混合',
		'sidebar/material/opacity': '透明度',
		'sidebar/material/transparent': '透明性',
		'sidebar/material/forcesinglepass': '强制单通道',
		'sidebar/material/alphatest': 'α测试',
		'sidebar/material/depthtest': '深度测试',
		'sidebar/material/depthwrite': '深度缓冲',
		'sidebar/material/wireframe': '线框',
		'sidebar/material/userdata': '自定义数据',
		'sidebar/material/export': '导出JSON',

		'sidebar/script/new': '新建',
		'sidebar/script/edit': '编辑',
		'sidebar/script/remove': '删除',

		'sidebar/project': "画布偏好",
		'sidebar/project/renderer': '渲染器',
		'sidebar/project/antialias': '抗锯齿',
		'sidebar/project/shadows': '阴影',
		'sidebar/project/toneMapping': '色调映射',
		'sidebar/project/geometries': '几何体',
		'sidebar/project/materials': '材质',
		'sidebar/project/textures': '纹理',
		'sidebar/project/Assign': '应用',

		'sidebar/project/app': "交互作品",
		'sidebar/project/app/play': '启动',
		'sidebar/project/app/stop': '暂停',
		'sidebar/project/app/title': '标题',
		'sidebar/project/app/editable': '编辑性',
		'sidebar/project/app/publish': '发布',

		'sidebar/project/image': '图片',
		'sidebar/project/image/samples': '样本',
		'sidebar/project/video': '视频',

		'sidebar/project/shading': '阴影',
		'sidebar/project/resolution': '分辨率',
		'sidebar/project/duration': '时长',
		'sidebar/project/render': '渲染',

		'sidebar/settings': "编辑习惯",
		'sidebar/settings/language': '语言',

		'sidebar/settings/shortcuts': '快捷键',
		'sidebar/settings/shortcuts/translate': '移动',
		'sidebar/settings/shortcuts/rotate': '旋转',
		'sidebar/settings/shortcuts/scale': '缩放',
		'sidebar/settings/shortcuts/undo': '撤销',
		'sidebar/settings/shortcuts/focus': '聚焦',
		'sidebar/settings/shortcuts/selectAll': '全选',

		'sidebar/history': '历史记录',
		'sidebar/history/clear': '清空',
		'sidebar/history/persistent': '本地存储',

		'toolbar/translate': '移动',
		'toolbar/rotate': '旋转',
		'toolbar/scale': '缩放',
		'toolbar/local': '本地',

		'viewport/controls/grid': '网格',
		'viewport/controls/helpers': '辅助',

		'viewport/info/object': '物体',
		'viewport/info/objects': '物体',
		'viewport/info/vertex': '顶点',
		'viewport/info/vertices': '顶点',
		'viewport/info/triangle': '三角形',
		'viewport/info/triangles': '三角形',
		'viewport/info/sample': '样本',
		'viewport/info/samples': '样本',
		'viewport/info/rendertime': '渲染时间',

		'script/title/vertexShader': '顶点着色器',
		'script/title/fragmentShader': '片段着色器',
		'script/title/programInfo': '程序属性',

		'dialog/gltf/title': "导入 GLB / glTF 模型",
		'dialog/gltf/asScene': "作为整个场景导入（替换当前场景，可撤销）",
		'dialog/texture/title': '纹理参数',
		'dialog/texture/group/preview': '预览',
		'dialog/texture/group/mapping': '映射',
		'dialog/texture/group/filtering': '过滤',
		'dialog/texture/group/transform': '变换',
		'dialog/texture/group/color': '颜色',
		'dialog/texture/mapping': '映射',
		'dialog/texture/wrapS': '环绕 S',
		'dialog/texture/wrapT': '环绕 T',
		'dialog/texture/magFilter': '放大过滤器',
		'dialog/texture/minFilter': '缩小过滤器',
		'dialog/texture/anisotropy': '各向异性',
		'dialog/texture/offset': '偏移',
		'dialog/texture/repeat': '重复',
		'dialog/texture/center': '中心',
		'dialog/texture/rotation': '旋转',
		'dialog/texture/premultiplyAlpha': '预乘 Alpha',
		'dialog/texture/colorSpace': '颜色空间',
		'dialog/ok': '确定',
		'dialog/cancel': '取消'

	};

	return {

		getKey: function ( key ) {

			return values[ key ] || '???';

		}

	};

}

export { Strings };
